name: "Test Branch Update Flow"
on:
  schedule:
    - cron:  '*/6 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v2
        with:
          ref: test
      - name: Push the old test branch 
        run: |
        if [[ -z "$string" ]]; then
        echo "String is empty"
        elif [[ -n "$string" ]]; then
        echo "String is not empty"
        fi

