name: "Test Branch Update Flow"
# on:
#   schedule:
#     - cron:  '5 * * * *'
on:
  push:
    branches:
      - master
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v2
        with:
          ref: test
      - name: Log something
        run: |
          echo "YEEEEEET Catbug"