name: "Test Branch Update Flow"
# on:
#   schedule:
#     - cron:  '5 * * * *'
on:
  push:
    branches:
      - master
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create new test branch
        run: |
          DATE=(date +%F)
          echo ${{env.DATE}}
          echo $(env.DATE)
          echo $(DATE)
          echo ${{DATE}}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b test-$(env.DATE)
          git push --set-upstream origin test-$(env.DATE)


#checkout master branch

#create and push new branch -test-date from master branch

# archive old  test branch
