name: "Test Branch Update Flow"
on:
  schedule:
    - cron:  '*/6 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v2
        with:
          ref: test
      - name: Push the old test branch 
        run: |
          date=$(date '+%F')
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b test-$date
          git push --set-upstream origin test-$date
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Archive old test branch
        run: |
          date=$(date '+%F')
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag archive/test-$date test-$date
          git branch -d test-$date
          git push origin :test-$date
          git push --tags
     